### PR TITLE
Add a model description with updated fowchart

### PR DESCRIPTION
**Pull request by Eleonore9**

### CODE REVIEW

**Comment by acron0** [comment]
@Eleonore9 We had a brief conversation about how the joiners step should be outside the loop - is this something you intend to adjust?

**Comment by seb231** [comment]
Does 'multiplier' need explaining? Multiplier to what?

**Comment by Eleonore9** [comment]
Good point @seb231!

**Comment by acron0** [comment]
I agree with seb's comment - some example numbers and what they mean (e.g. "1.0" is 100% of the defaault value, therefore "0.2" is an...80% reduction? IANAM!)

**Comment by Eleonore9** [comment]
Good idea @acron0 ! Updated the text again.

**Pull request merged**
